//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool (mirrors what Visual Studio emits for
//     a Web Forms page's designer file).
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductsApp
{
    public partial class Default
    {
        protected global::System.Web.UI.WebControls.GridView ProductsGridView;

        protected global::System.Web.UI.WebControls.Label StatusLabel;
    }
}
