//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool (mirrors what Visual Studio emits for
//     a Web Forms page's designer file).
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductsApp
{
    public partial class ProductDetail
    {
        protected global::System.Web.UI.WebControls.Panel DetailPanel;

        protected global::System.Web.UI.WebControls.Literal NameLiteral;

        protected global::System.Web.UI.WebControls.Literal CategoryLiteral;

        protected global::System.Web.UI.WebControls.Literal PriceLiteral;

        protected global::System.Web.UI.WebControls.Literal InStockLiteral;

        protected global::System.Web.UI.WebControls.Literal CreatedLiteral;

        protected global::System.Web.UI.WebControls.Label NotFoundLabel;
    }
}
