//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool (mirrors what Visual Studio emits for
//     a Web Forms page's designer file).
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductsApp
{
    public partial class ProductCreate
    {
        protected global::System.Web.UI.WebControls.TextBox NameTextBox;

        protected global::System.Web.UI.WebControls.RequiredFieldValidator NameRequiredValidator;

        protected global::System.Web.UI.WebControls.TextBox CategoryTextBox;

        protected global::System.Web.UI.WebControls.RequiredFieldValidator CategoryRequiredValidator;

        protected global::System.Web.UI.WebControls.TextBox PriceTextBox;

        protected global::System.Web.UI.WebControls.RequiredFieldValidator PriceRequiredValidator;

        protected global::System.Web.UI.WebControls.RangeValidator PriceRangeValidator;

        protected global::System.Web.UI.WebControls.CheckBox InStockCheckBox;

        protected global::System.Web.UI.WebControls.Button SaveButton;

        protected global::System.Web.UI.WebControls.Label StatusLabel;
    }
}
