//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool (mirrors what Visual Studio emits for
//     a Web Forms master page's designer file).
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductsApp
{
    public partial class SiteMaster
    {
        /// <summary>
        /// HeadContent control.
        /// </summary>
        protected global::System.Web.UI.WebControls.ContentPlaceHolder HeadContent;

        /// <summary>
        /// MainContent control.
        /// </summary>
        protected global::System.Web.UI.WebControls.ContentPlaceHolder MainContent;
    }
}
